### PR TITLE
fix #144 eventpage consistent language and errors

### LINKED ISSUE #144: Consistent German language and meaningful error messages "Veranstaltungs"-page
**As** 
user 

**I want to** 
have consistent german language on the "Veranstaltungs"-page and meaningful error messages

**in order to** 
have a great user experience. 

**5 🍪**

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features.

- [ ] There is no mix of languages for names of input fields, error messages and the like
- [ ] I get error messages that explain what went wrong and what i can do to fix it

### PR DESCRIPTION
**Pull request by GoesOnTangents**

### CODE REVIEW

File: app/models/date_range.rb [hunk 1]
```diff
@@ -20,24 +20,24 @@ class DateRange < ActiveRecord::Base
 
   def validate_start_date_not_in_past
     if start_date < Date.today
-      errors.add(:start_date, "darf nicht in der Vergangenheit liegen.")
+      errors.add(:start_date, I18n.t("date_range.errors.starts_in past"))
     end
     if end_date < Date.today
-      errors.add(:end_date, "darf nicht in der Vergangenheit liegen.")
+      errors.add(:end_date, I18n.t("date_range.errors."))
```
Comment (bjrne) [inline app/models/date_range.rb]: This doesn't seem correct, does it?

File: app/views/events/index.html.erb [hunk 2]
```diff
@@ -29,7 +29,7 @@
           <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                       event_path(event),
                       :method => :delete,
-                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
+                      :data => { :confirm => t('events.confirmation_prompts.confirm_delete', :default => t("helpers.links.confirm", :default => 'Löschen kann nicht rückgängig gemacht werden!')) },
```
Comment (bjrne) [inline app/views/events/index.html.erb]: Still some german in the code, is this intentional?

File: app/views/events/participants.html.erb [hunk 3]
```diff
@@ -36,6 +36,6 @@
   </table>
   
   
-  <%= link_to t('.back', :default => t("helpers.links.back")),
+  <%= link_to t('.back', :default => t('helpers.links.back')),
```
Comment (bjrne) [inline app/views/events/participants.html.erb]: This is almost the only place you use single quotes. I'm not really familiar with what Ruby expects, but wound't it make sense to have everything the same way at least? From what I heard, Ruby prefers single quotes over double quotes whenever possible.

Comment (MasterCarl) [inline app/views/events/participants.html.erb]: This is what I heard as well, double quoted strings should only be used for string interpolation

**Review by MasterCarl — DISMISSED** [review]
I'm adding a formal request for changes

File: app/models/date_range.rb (hunk 1 above)
Comment (KBorchar) [inline app/models/date_range.rb]: Fixed now, thanks.

File: app/views/events/index.html.erb [hunk 4]
```diff
@@ -19,19 +19,19 @@
       <tr>
         <td><%= link_to event.id, event_path(event) %></td>
         <td><%= event.name %></td>
-        <td><%= event.kind %></td>
+        <td><%= I18n.t "events.kinds.#{event.kind}" %></td>
```
Comment (bjrne) [inline app/views/events/index.html.erb]: Did you forget this or is it necessary to have double quotes here?

File: spec/features/event_spec.rb [hunk 5]
```diff
@@ -17,7 +17,7 @@
       select_date_within_selector(Date.yesterday.prev_day, '.event-date-picker-start')
       select_date_within_selector(Date.yesterday, '.event-date-picker-end')
       click_button I18n.t('.events.form.publish')
-      expect(page).to have_text("Anfangs-Datum darf nicht in der Vergangenheit liegen.")
+      expect(page).to have_text("Anfangs-Datum darf nicht in der Vergangenheit liegen")
```
Comment (bjrne) [inline spec/features/event_spec.rb]: single quotes?

File: spec/views/events/index.html.erb_spec.rb [hunk 6]
```diff
@@ -9,7 +9,7 @@
   it "displays the name, the eventkind, the timespan and the status" do
     render
     assert_select "td", :text => @event.name
-    assert_select "td", :text => @event.kind
+    assert_select "td", :text => I18n.t("events.kinds.#{@event.kind}")
```
Comment (bjrne) [inline spec/views/events/index.html.erb_spec.rb]: same as above, is this necessary?

File: config/locales/de.date_ranges.yml [hunk 7]
```diff
@@ -2,7 +2,14 @@
 
 de:
   date_range:
-    to: "bis"
+    errors:
+      starts_in_past: "Anfangs-Datum darf nicht in der Vergangenheit liegen"
+      end_in_past: "darf nicht in der Vergangenheit liegen"
+      end_before_start: "kann nicht vor Start-Datum liegen"
+      no_timespan: "Bitte mindestens eine Zeitspanne auswählen"
```
Comment (bjrne) [inline config/locales/de.date_ranges.yml]: Do translations need to be double-quoted? Just because everyone obviously does it this way does not necessarily mean they needs to be.

**Review by bjrne — CHANGES_REQUESTED** [review]

File: app/views/events/index.html.erb (hunk 4 above)
Comment (KBorchar) [inline app/views/events/index.html.erb]: Tests only validate with double quotes here

File: spec/views/events/index.html.erb_spec.rb (hunk 6 above)
Comment (KBorchar) [inline spec/views/events/index.html.erb_spec.rb]: Same as above :)

**Review by bjrne — APPROVED** [review]
